### ISSUE TITLE
Frontend TODO list

### ISSUE THREAD

**Issue by t0m4s79** [ramartins02/DREFleet#51]
- [ ] Route optimization (see #71)
- [ ] Bulk actions (delete, mark as read, approve/unapprove, ...)
- [x] Places -> On page load a waypoint is being inserted at 0,0 coordinates -> needs fixing
- [x] Places -> if coordinates fields are changed, waypoint should update (these fields should also follow the bounds rule)
- [x] Approve and unapprove orders buttons
- [x] Managers page with all orders approved by a specific manager
- [x] Leaflet map route instructions to Portuguese
- [x] Vehicle create form, disable options if vehicle is not a heavy vehicle
- [x] MANAGERS FRONTEND TABLE SHOULD HAVE LINK FOR ALL APPROVED ORDERS BY HIM
- [x] Create new page for routes
- [x] Add Modal to show order route trajectory
- [x] Bounds in Places Map
- [x] Create LandingPage
- [x] Create Reports tab
- [ ] Image select in Vehicle create/edit page
- [x] License Number in Drivers create/edit page
- [x]  Add all routes page
- [x]  Change Edit pages to have a button to allow edit -> at first just show info
- [x] Redo NewOrderRoutes -> new backend model
- [x] Expiration Dates in red if already expired (accessories, documents, drivers)
- [x] Links to entities in id columns of table
- [x] Change mui-color-input to react-colorful or react-color
- [x] Trajectory is not being updated correctly in NewOrder and EditOrder -> Check WaypointManager and ExperimentalMap
- [x] Vehicle accessories and documents page
- [x] Kid create and edit email pages
- [x] Kid create and edit phone number pages
- [x] Kid contacts page
- [x] Route showing on order maps
- [x] Routes table showing drivers and technicians
- [ ] Notifications table and mark as read button
    - [x] After clicking mark as read remove need to refresh page to see changes on notifications table
    - [x] After clicking mark as read remove need to refresh page to see changes on notifications count
    - [ ] PING sound when notification received and message on screen
- [x] Loading Modals (DRIFTING VAN GO VROOOOOOOOOM)
- [x] Vehicle Documents with new data field in index, create and edit pages
- [x] Order Occurrences showing pop-up with description
- [x] Order and routes edit page disabled fields
- [x] Correctly order dates on tables
- [ ] #89
- [x] Item individual cost in vehicle maintenance reports edit and creation pages (see code comments)
- [x] Show status according to date values in vehicle maintenance reports edit and creation pages (see back-end logic)
- [x] Popup with description in specific vehicle maintenance reports page (see code comments)
- [x] Disable draggable places in orders
- [x] Cancel edit should return values to original
- [x] Map route to PT
- [x] Driver tcc expiration date should be set to null when tcc is 0
- [ ] Dashboard revamp -> "Clients" want a more detailed dashboard

**Comment by t0m4s79** [comment]
Trajectory seems to be updating properly. Further testing is required to make sure it is working properly. Maybe using real data could reveal if there are any inconsistencies.

**Comment by t0m4s79** [comment]
react-beautiful-dnd is now deprecated. Context and options: 
[](https://github.com/atlassian/react-beautiful-dnd/issues/2672)

There is the possibility of continuing to use it, by forking the repo or migrate to a new alternative package.
I am thinking of migrating to their new [Pragmatic drag and drop](https://github.com/atlassian/pragmatic-drag-and-drop)

**Comment by t0m4s79** [comment]
From what was told on the last meeting, Maintenance Reports do not require materials, items cost. A simple description should be enough to describe what was done in terms of maintenance.
