### ISSUE TITLE
Back-end TODO List

### ISSUE THREAD

**Issue by ramartins02** [ramartins02/DREFleet#52]
- [ ] USER VERIFICATION ON CREATES, EDITS AND DELETES (MUST BE AUTHENCTICATED, MUST BE A CERTAIN USER_TYPE,...);
- [ ] Page caches
- [x] Test job scheduling
- [ ] Route optimization (see #71)
- [x] Start inserting logs in code
- [x] Orders actual date fields
- [x] User and vehicle availability validation in orders creation/edit
- [x] Refactor Rules tests
- [ ] Logs on notifications and jobs

*****************************************
Images
- [ ] Check if images in storage can be accessed through web

*****************************************
VehicleController
- [ ] Resize images before storing

*****************************************
TABLES:
- [ ] Maintenance Reports
    - [x] Migrations
    - [x] CRUD logic
    - [ ] Front-end pages (still need completion)
    - [x] Unit tests
    - [ ] Notifications
    - [ ] Jobs
- [ ] Vehicle Reports
- [ ] Order Reports
- [ ] Manager needs to approve refuel request from 7 requests onwards

**Comment by t0m4s79** [comment]
OrderStops is missing `kid_id` property. This makes it so that inspecting an order does not show kid information in each "waypoint"
